### ISSUE TITLE
Event broker config supports only Pika

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/helm-charts#103]
I want the following event broker config in `endpoints.yml` but the helm chart doesn't allow this:

```yml
event_broker:
  type: file
  logger_file: rasa_events.json
```

The template is configured to always emit the Rabbit related event broker values which will be rejected by the file broker and rasa will not start.
