### ISSUE TITLE
Rasa Chart currently requires Bitnami Charts that are no longer available

### ISSUE THREAD

**Issue by laberning** [RasaHQ/helm-charts#119]
Currently the Rasa Chart uses the following dependencies

| Repository | Name | Version |
|------------|------|---------|
| https://charts.bitnami.com/bitnami | postgresql | ~10.16.2 |
| https://charts.bitnami.com/bitnami | rabbitmq | ~8.32.2 |
| https://charts.bitnami.com/bitnami | redis | ~15.7.6 |

All those are no longer available, so a `helm dependency update` fails with unmatchable requirements.

Updating the Charts to the versions below works, but requires tweaking the postgresql configuration a bit, since the name and defaults for keys in the secrets have changed with the new bitnami charts:

```
postgresql:
  ...
  # used to be "postgresql-password" in older versions of the bitnami charts
  existingSecretKey: postgres-password
  auth:
    username: "postgres"
    database: "rasa"
```

| Repository | Name | Version |
|------------|------|---------|
| https://charts.bitnami.com/bitnami | postgresql | ~12.2.1 |
| https://charts.bitnami.com/bitnami | rabbitmq | ~11.10.0 |
| https://charts.bitnami.com/bitnami | redis | ~17.8.0 |
