### ISSUE TITLE
Kafka eventBroker setting still insert rabbit env vars

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/helm-charts#122]
When the key `data.endpoints.eventBroker.type` is set to `kafka`, the following default Rabbit related values should not be set:

```yml
      password: ${RABBITMQ_PASSWORD}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
```
