### ISSUE TITLE
Cannot set rasaXToken, rasaToken and JWT_SECRET from custom secret

### ISSUE THREAD

**Issue by nyejon** [RasaHQ/helm-charts#71]
Hi,

The helm chart doesn't seem to allow setting custom secrets for these values outside of the values file like the Rasa X Helm chart allows.

It would also help to have the naming between the different charts aligned, as it is very confusing dealing with multiple names referring to the same thing, across the charts.

Thanks,
Jonathan

**Comment by sara-tagger** [comment]
Thanks for the issue, @kedz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by nyejon** [comment]
This could be updated to allow referencing a custom secret provider:
https://github.com/RasaHQ/helm-charts/blob/main/charts/rasa/templates/_containers-env.yaml

**Comment by nyejon** [comment]
See https://github.com/RasaHQ/rasa-x-helm/blob/68b36820918c26074fe662491150e821baf64d20/charts/rasa-x/templates/rasa-deployments.yaml#L115 for an example.

**Comment by nyejon** [comment]
https://github.com/RasaHQ/helm-charts/blob/main/examples/rasa/README.md this example doesn't work because of the broken secrets.

This chart requires so many hacks and poor practices to get working.

Come on Rasa, all we want to do is put the best chatbot software into use.
These poor-quality charts make this process much harder than it needs to be and sour the great user experience generated by the chatbot development.

**Comment by nyejon** [comment]
You can avoid this by adding the following envs to your pods manually:
``` 
extraEnv:
      - name: "RASA_MODEL_SERVER"
        value: MODEL_SERVER_URL
      # See: https://github.com/RasaHQ/helm-charts/issues/71 for the tokens being made available with custom secret
      - name: RASA_X_TOKEN
        valueFrom:
          secretKeyRef:
            name: rasa-secret
            key: "rasaXToken"
      - name: RASA_TOKEN
        valueFrom:
          secretKeyRef:
            name: rasa-secret
            key: "rasaToken"
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: rasaal-secret
            key: "jwtSecret"
      - name: "DB_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: rasa-secret
            key: RASAX_POSTGRES_PASSWORD
      - name: "DB_DATABASE"
        value: "rasa"
      - name: "REDIS_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: rasa-secret
            key: "REDIS_PASSWORD"
      - name: "RABBITMQ_QUEUE"
        value: rasa_production_events
      - name: "RABBITMQ_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: rasa-secret
            key: rabbitmq-password
      # This needs to be added here because of this issue: https://github.com/RasaHQ/helm-charts/issues/76
      - name: “RASA_DUCKLING_HTTP_URL”
        value: “http://rasa-x-duckling.mal-development:8000”
```

It still results in double the ENV's being created for some of them, one of the values being UNSET, but for now it seems to work.
